name: Cache-Simple-TimedExpiry
version: 0.20
abstract: A lightweight cache with timed expiration
author: Robert Spier <rspier@pobox.com>, Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
requires:
  perl: 5.005
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
